// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msginfo.proto

#ifndef PROTOBUF_msginfo_2eproto__INCLUDED
#define PROTOBUF_msginfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace msginfo {
class CMsg;
class CMsgDefaultTypeInternal;
extern CMsgDefaultTypeInternal _CMsg_default_instance_;
class CMsgHead;
class CMsgHeadDefaultTypeInternal;
extern CMsgHeadDefaultTypeInternal _CMsgHead_default_instance_;
class CMsgLogin;
class CMsgLoginDefaultTypeInternal;
extern CMsgLoginDefaultTypeInternal _CMsgLogin_default_instance_;
class CMsgLogout;
class CMsgLogoutDefaultTypeInternal;
extern CMsgLogoutDefaultTypeInternal _CMsgLogout_default_instance_;
class CMsgReg;
class CMsgRegDefaultTypeInternal;
extern CMsgRegDefaultTypeInternal _CMsgReg_default_instance_;
}  // namespace msginfo

namespace msginfo {

namespace protobuf_msginfo_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_msginfo_2eproto

// ===================================================================

class CMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msginfo.CMsg) */ {
 public:
  CMsg();
  virtual ~CMsg();

  CMsg(const CMsg& from);

  inline CMsg& operator=(const CMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsg& default_instance();

  static inline const CMsg* internal_default_instance() {
    return reinterpret_cast<const CMsg*>(
               &_CMsg_default_instance_);
  }

  void Swap(CMsg* other);

  // implements Message ----------------------------------------------

  inline CMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsg& from);
  void MergeFrom(const CMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string msghead = 1;
  bool has_msghead() const;
  void clear_msghead();
  static const int kMsgheadFieldNumber = 1;
  const ::std::string& msghead() const;
  void set_msghead(const ::std::string& value);
  #if LANG_CXX11
  void set_msghead(::std::string&& value);
  #endif
  void set_msghead(const char* value);
  void set_msghead(const char* value, size_t size);
  ::std::string* mutable_msghead();
  ::std::string* release_msghead();
  void set_allocated_msghead(::std::string* msghead);

  // required string msgbody = 2;
  bool has_msgbody() const;
  void clear_msgbody();
  static const int kMsgbodyFieldNumber = 2;
  const ::std::string& msgbody() const;
  void set_msgbody(const ::std::string& value);
  #if LANG_CXX11
  void set_msgbody(::std::string&& value);
  #endif
  void set_msgbody(const char* value);
  void set_msgbody(const char* value, size_t size);
  ::std::string* mutable_msgbody();
  ::std::string* release_msgbody();
  void set_allocated_msgbody(::std::string* msgbody);

  // @@protoc_insertion_point(class_scope:msginfo.CMsg)
 private:
  void set_has_msghead();
  void clear_has_msghead();
  void set_has_msgbody();
  void clear_has_msgbody();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msghead_;
  ::google::protobuf::internal::ArenaStringPtr msgbody_;
  friend struct  protobuf_msginfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CMsgHead : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msginfo.CMsgHead) */ {
 public:
  CMsgHead();
  virtual ~CMsgHead();

  CMsgHead(const CMsgHead& from);

  inline CMsgHead& operator=(const CMsgHead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgHead& default_instance();

  static inline const CMsgHead* internal_default_instance() {
    return reinterpret_cast<const CMsgHead*>(
               &_CMsgHead_default_instance_);
  }

  void Swap(CMsgHead* other);

  // implements Message ----------------------------------------------

  inline CMsgHead* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgHead* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgHead& from);
  void MergeFrom(const CMsgHead& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgHead* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string termid = 6;
  bool has_termid() const;
  void clear_termid();
  static const int kTermidFieldNumber = 6;
  const ::std::string& termid() const;
  void set_termid(const ::std::string& value);
  #if LANG_CXX11
  void set_termid(::std::string&& value);
  #endif
  void set_termid(const char* value);
  void set_termid(const char* value, size_t size);
  ::std::string* mutable_termid();
  ::std::string* release_termid();
  void set_allocated_termid(::std::string* termid);

  // required int32 msglen = 1;
  bool has_msglen() const;
  void clear_msglen();
  static const int kMsglenFieldNumber = 1;
  ::google::protobuf::int32 msglen() const;
  void set_msglen(::google::protobuf::int32 value);

  // required int32 msgtype = 2;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgtypeFieldNumber = 2;
  ::google::protobuf::int32 msgtype() const;
  void set_msgtype(::google::protobuf::int32 value);

  // required int32 msgseq = 3;
  bool has_msgseq() const;
  void clear_msgseq();
  static const int kMsgseqFieldNumber = 3;
  ::google::protobuf::int32 msgseq() const;
  void set_msgseq(::google::protobuf::int32 value);

  // required int32 termversion = 4;
  bool has_termversion() const;
  void clear_termversion();
  static const int kTermversionFieldNumber = 4;
  ::google::protobuf::int32 termversion() const;
  void set_termversion(::google::protobuf::int32 value);

  // required int32 msgres = 5;
  bool has_msgres() const;
  void clear_msgres();
  static const int kMsgresFieldNumber = 5;
  ::google::protobuf::int32 msgres() const;
  void set_msgres(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msginfo.CMsgHead)
 private:
  void set_has_msglen();
  void clear_has_msglen();
  void set_has_msgtype();
  void clear_has_msgtype();
  void set_has_msgseq();
  void clear_has_msgseq();
  void set_has_termversion();
  void clear_has_termversion();
  void set_has_msgres();
  void clear_has_msgres();
  void set_has_termid();
  void clear_has_termid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr termid_;
  ::google::protobuf::int32 msglen_;
  ::google::protobuf::int32 msgtype_;
  ::google::protobuf::int32 msgseq_;
  ::google::protobuf::int32 termversion_;
  ::google::protobuf::int32 msgres_;
  friend struct  protobuf_msginfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CMsgReg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msginfo.CMsgReg) */ {
 public:
  CMsgReg();
  virtual ~CMsgReg();

  CMsgReg(const CMsgReg& from);

  inline CMsgReg& operator=(const CMsgReg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgReg& default_instance();

  static inline const CMsgReg* internal_default_instance() {
    return reinterpret_cast<const CMsgReg*>(
               &_CMsgReg_default_instance_);
  }

  void Swap(CMsgReg* other);

  // implements Message ----------------------------------------------

  inline CMsgReg* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgReg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgReg& from);
  void MergeFrom(const CMsgReg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgReg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string termid = 5 [default = "12345"];
  bool has_termid() const;
  void clear_termid();
  static const int kTermidFieldNumber = 5;
  const ::std::string& termid() const;
  void set_termid(const ::std::string& value);
  #if LANG_CXX11
  void set_termid(::std::string&& value);
  #endif
  void set_termid(const char* value);
  void set_termid(const char* value, size_t size);
  ::std::string* mutable_termid();
  ::std::string* release_termid();
  void set_allocated_termid(::std::string* termid);

  // optional int32 area = 1;
  bool has_area() const;
  void clear_area();
  static const int kAreaFieldNumber = 1;
  ::google::protobuf::int32 area() const;
  void set_area(::google::protobuf::int32 value);

  // optional int32 region = 2;
  bool has_region() const;
  void clear_region();
  static const int kRegionFieldNumber = 2;
  ::google::protobuf::int32 region() const;
  void set_region(::google::protobuf::int32 value);

  // optional int32 shop = 3;
  bool has_shop() const;
  void clear_shop();
  static const int kShopFieldNumber = 3;
  ::google::protobuf::int32 shop() const;
  void set_shop(::google::protobuf::int32 value);

  // optional int32 ret = 4;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 4;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msginfo.CMsgReg)
 private:
  void set_has_area();
  void clear_has_area();
  void set_has_region();
  void clear_has_region();
  void set_has_shop();
  void clear_has_shop();
  void set_has_ret();
  void clear_has_ret();
  void set_has_termid();
  void clear_has_termid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _default_termid_;
  ::google::protobuf::internal::ArenaStringPtr termid_;
  ::google::protobuf::int32 area_;
  ::google::protobuf::int32 region_;
  ::google::protobuf::int32 shop_;
  ::google::protobuf::int32 ret_;
  friend struct  protobuf_msginfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CMsgLogin : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msginfo.CMsgLogin) */ {
 public:
  CMsgLogin();
  virtual ~CMsgLogin();

  CMsgLogin(const CMsgLogin& from);

  inline CMsgLogin& operator=(const CMsgLogin& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgLogin& default_instance();

  static inline const CMsgLogin* internal_default_instance() {
    return reinterpret_cast<const CMsgLogin*>(
               &_CMsgLogin_default_instance_);
  }

  void Swap(CMsgLogin* other);

  // implements Message ----------------------------------------------

  inline CMsgLogin* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgLogin* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgLogin& from);
  void MergeFrom(const CMsgLogin& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgLogin* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msginfo.CMsgLogin)
 private:
  void set_has_ret();
  void clear_has_ret();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend struct  protobuf_msginfo_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CMsgLogout : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msginfo.CMsgLogout) */ {
 public:
  CMsgLogout();
  virtual ~CMsgLogout();

  CMsgLogout(const CMsgLogout& from);

  inline CMsgLogout& operator=(const CMsgLogout& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgLogout& default_instance();

  static inline const CMsgLogout* internal_default_instance() {
    return reinterpret_cast<const CMsgLogout*>(
               &_CMsgLogout_default_instance_);
  }

  void Swap(CMsgLogout* other);

  // implements Message ----------------------------------------------

  inline CMsgLogout* New() const PROTOBUF_FINAL { return New(NULL); }

  CMsgLogout* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CMsgLogout& from);
  void MergeFrom(const CMsgLogout& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CMsgLogout* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ret = 1;
  bool has_ret() const;
  void clear_ret();
  static const int kRetFieldNumber = 1;
  ::google::protobuf::int32 ret() const;
  void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msginfo.CMsgLogout)
 private:
  void set_has_ret();
  void clear_has_ret();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend struct  protobuf_msginfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMsg

// required string msghead = 1;
inline bool CMsg::has_msghead() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsg::set_has_msghead() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsg::clear_has_msghead() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsg::clear_msghead() {
  msghead_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msghead();
}
inline const ::std::string& CMsg::msghead() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsg.msghead)
  return msghead_.GetNoArena();
}
inline void CMsg::set_msghead(const ::std::string& value) {
  set_has_msghead();
  msghead_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msginfo.CMsg.msghead)
}
#if LANG_CXX11
inline void CMsg::set_msghead(::std::string&& value) {
  set_has_msghead();
  msghead_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msginfo.CMsg.msghead)
}
#endif
inline void CMsg::set_msghead(const char* value) {
  set_has_msghead();
  msghead_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msginfo.CMsg.msghead)
}
inline void CMsg::set_msghead(const char* value, size_t size) {
  set_has_msghead();
  msghead_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msginfo.CMsg.msghead)
}
inline ::std::string* CMsg::mutable_msghead() {
  set_has_msghead();
  // @@protoc_insertion_point(field_mutable:msginfo.CMsg.msghead)
  return msghead_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsg::release_msghead() {
  // @@protoc_insertion_point(field_release:msginfo.CMsg.msghead)
  clear_has_msghead();
  return msghead_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsg::set_allocated_msghead(::std::string* msghead) {
  if (msghead != NULL) {
    set_has_msghead();
  } else {
    clear_has_msghead();
  }
  msghead_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msghead);
  // @@protoc_insertion_point(field_set_allocated:msginfo.CMsg.msghead)
}

// required string msgbody = 2;
inline bool CMsg::has_msgbody() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsg::set_has_msgbody() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsg::clear_has_msgbody() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsg::clear_msgbody() {
  msgbody_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msgbody();
}
inline const ::std::string& CMsg::msgbody() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsg.msgbody)
  return msgbody_.GetNoArena();
}
inline void CMsg::set_msgbody(const ::std::string& value) {
  set_has_msgbody();
  msgbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msginfo.CMsg.msgbody)
}
#if LANG_CXX11
inline void CMsg::set_msgbody(::std::string&& value) {
  set_has_msgbody();
  msgbody_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msginfo.CMsg.msgbody)
}
#endif
inline void CMsg::set_msgbody(const char* value) {
  set_has_msgbody();
  msgbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msginfo.CMsg.msgbody)
}
inline void CMsg::set_msgbody(const char* value, size_t size) {
  set_has_msgbody();
  msgbody_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msginfo.CMsg.msgbody)
}
inline ::std::string* CMsg::mutable_msgbody() {
  set_has_msgbody();
  // @@protoc_insertion_point(field_mutable:msginfo.CMsg.msgbody)
  return msgbody_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsg::release_msgbody() {
  // @@protoc_insertion_point(field_release:msginfo.CMsg.msgbody)
  clear_has_msgbody();
  return msgbody_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsg::set_allocated_msgbody(::std::string* msgbody) {
  if (msgbody != NULL) {
    set_has_msgbody();
  } else {
    clear_has_msgbody();
  }
  msgbody_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgbody);
  // @@protoc_insertion_point(field_set_allocated:msginfo.CMsg.msgbody)
}

// -------------------------------------------------------------------

// CMsgHead

// required int32 msglen = 1;
inline bool CMsgHead::has_msglen() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgHead::set_has_msglen() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgHead::clear_has_msglen() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgHead::clear_msglen() {
  msglen_ = 0;
  clear_has_msglen();
}
inline ::google::protobuf::int32 CMsgHead::msglen() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.msglen)
  return msglen_;
}
inline void CMsgHead::set_msglen(::google::protobuf::int32 value) {
  set_has_msglen();
  msglen_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.msglen)
}

// required int32 msgtype = 2;
inline bool CMsgHead::has_msgtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgHead::set_has_msgtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgHead::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgHead::clear_msgtype() {
  msgtype_ = 0;
  clear_has_msgtype();
}
inline ::google::protobuf::int32 CMsgHead::msgtype() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.msgtype)
  return msgtype_;
}
inline void CMsgHead::set_msgtype(::google::protobuf::int32 value) {
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.msgtype)
}

// required int32 msgseq = 3;
inline bool CMsgHead::has_msgseq() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgHead::set_has_msgseq() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgHead::clear_has_msgseq() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgHead::clear_msgseq() {
  msgseq_ = 0;
  clear_has_msgseq();
}
inline ::google::protobuf::int32 CMsgHead::msgseq() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.msgseq)
  return msgseq_;
}
inline void CMsgHead::set_msgseq(::google::protobuf::int32 value) {
  set_has_msgseq();
  msgseq_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.msgseq)
}

// required int32 termversion = 4;
inline bool CMsgHead::has_termversion() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgHead::set_has_termversion() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgHead::clear_has_termversion() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgHead::clear_termversion() {
  termversion_ = 0;
  clear_has_termversion();
}
inline ::google::protobuf::int32 CMsgHead::termversion() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.termversion)
  return termversion_;
}
inline void CMsgHead::set_termversion(::google::protobuf::int32 value) {
  set_has_termversion();
  termversion_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.termversion)
}

// required int32 msgres = 5;
inline bool CMsgHead::has_msgres() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CMsgHead::set_has_msgres() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CMsgHead::clear_has_msgres() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CMsgHead::clear_msgres() {
  msgres_ = 0;
  clear_has_msgres();
}
inline ::google::protobuf::int32 CMsgHead::msgres() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.msgres)
  return msgres_;
}
inline void CMsgHead::set_msgres(::google::protobuf::int32 value) {
  set_has_msgres();
  msgres_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.msgres)
}

// required string termid = 6;
inline bool CMsgHead::has_termid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgHead::set_has_termid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgHead::clear_has_termid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgHead::clear_termid() {
  termid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_termid();
}
inline const ::std::string& CMsgHead::termid() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgHead.termid)
  return termid_.GetNoArena();
}
inline void CMsgHead::set_termid(const ::std::string& value) {
  set_has_termid();
  termid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:msginfo.CMsgHead.termid)
}
#if LANG_CXX11
inline void CMsgHead::set_termid(::std::string&& value) {
  set_has_termid();
  termid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msginfo.CMsgHead.termid)
}
#endif
inline void CMsgHead::set_termid(const char* value) {
  set_has_termid();
  termid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msginfo.CMsgHead.termid)
}
inline void CMsgHead::set_termid(const char* value, size_t size) {
  set_has_termid();
  termid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msginfo.CMsgHead.termid)
}
inline ::std::string* CMsgHead::mutable_termid() {
  set_has_termid();
  // @@protoc_insertion_point(field_mutable:msginfo.CMsgHead.termid)
  return termid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMsgHead::release_termid() {
  // @@protoc_insertion_point(field_release:msginfo.CMsgHead.termid)
  clear_has_termid();
  return termid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMsgHead::set_allocated_termid(::std::string* termid) {
  if (termid != NULL) {
    set_has_termid();
  } else {
    clear_has_termid();
  }
  termid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), termid);
  // @@protoc_insertion_point(field_set_allocated:msginfo.CMsgHead.termid)
}

// -------------------------------------------------------------------

// CMsgReg

// optional int32 area = 1;
inline bool CMsgReg::has_area() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgReg::set_has_area() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgReg::clear_has_area() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgReg::clear_area() {
  area_ = 0;
  clear_has_area();
}
inline ::google::protobuf::int32 CMsgReg::area() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgReg.area)
  return area_;
}
inline void CMsgReg::set_area(::google::protobuf::int32 value) {
  set_has_area();
  area_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgReg.area)
}

// optional int32 region = 2;
inline bool CMsgReg::has_region() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgReg::set_has_region() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgReg::clear_has_region() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgReg::clear_region() {
  region_ = 0;
  clear_has_region();
}
inline ::google::protobuf::int32 CMsgReg::region() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgReg.region)
  return region_;
}
inline void CMsgReg::set_region(::google::protobuf::int32 value) {
  set_has_region();
  region_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgReg.region)
}

// optional int32 shop = 3;
inline bool CMsgReg::has_shop() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgReg::set_has_shop() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgReg::clear_has_shop() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgReg::clear_shop() {
  shop_ = 0;
  clear_has_shop();
}
inline ::google::protobuf::int32 CMsgReg::shop() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgReg.shop)
  return shop_;
}
inline void CMsgReg::set_shop(::google::protobuf::int32 value) {
  set_has_shop();
  shop_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgReg.shop)
}

// optional int32 ret = 4;
inline bool CMsgReg::has_ret() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CMsgReg::set_has_ret() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CMsgReg::clear_has_ret() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CMsgReg::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 CMsgReg::ret() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgReg.ret)
  return ret_;
}
inline void CMsgReg::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgReg.ret)
}

// optional string termid = 5 [default = "12345"];
inline bool CMsgReg::has_termid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgReg::set_has_termid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgReg::clear_has_termid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgReg::clear_termid() {
  termid_.ClearToDefaultNoArena(&CMsgReg::_default_termid_.get());
  clear_has_termid();
}
inline const ::std::string& CMsgReg::termid() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgReg.termid)
  return termid_.GetNoArena();
}
inline void CMsgReg::set_termid(const ::std::string& value) {
  set_has_termid();
  termid_.SetNoArena(&CMsgReg::_default_termid_.get(), value);
  // @@protoc_insertion_point(field_set:msginfo.CMsgReg.termid)
}
#if LANG_CXX11
inline void CMsgReg::set_termid(::std::string&& value) {
  set_has_termid();
  termid_.SetNoArena(
    &CMsgReg::_default_termid_.get(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:msginfo.CMsgReg.termid)
}
#endif
inline void CMsgReg::set_termid(const char* value) {
  set_has_termid();
  termid_.SetNoArena(&CMsgReg::_default_termid_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:msginfo.CMsgReg.termid)
}
inline void CMsgReg::set_termid(const char* value, size_t size) {
  set_has_termid();
  termid_.SetNoArena(&CMsgReg::_default_termid_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:msginfo.CMsgReg.termid)
}
inline ::std::string* CMsgReg::mutable_termid() {
  set_has_termid();
  // @@protoc_insertion_point(field_mutable:msginfo.CMsgReg.termid)
  return termid_.MutableNoArena(&CMsgReg::_default_termid_.get());
}
inline ::std::string* CMsgReg::release_termid() {
  // @@protoc_insertion_point(field_release:msginfo.CMsgReg.termid)
  clear_has_termid();
  return termid_.ReleaseNoArena(&CMsgReg::_default_termid_.get());
}
inline void CMsgReg::set_allocated_termid(::std::string* termid) {
  if (termid != NULL) {
    set_has_termid();
  } else {
    clear_has_termid();
  }
  termid_.SetAllocatedNoArena(&CMsgReg::_default_termid_.get(), termid);
  // @@protoc_insertion_point(field_set_allocated:msginfo.CMsgReg.termid)
}

// -------------------------------------------------------------------

// CMsgLogin

// optional int32 ret = 1;
inline bool CMsgLogin::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgLogin::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgLogin::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgLogin::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 CMsgLogin::ret() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgLogin.ret)
  return ret_;
}
inline void CMsgLogin::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgLogin.ret)
}

// -------------------------------------------------------------------

// CMsgLogout

// optional int32 ret = 1;
inline bool CMsgLogout::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgLogout::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgLogout::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgLogout::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 CMsgLogout::ret() const {
  // @@protoc_insertion_point(field_get:msginfo.CMsgLogout.ret)
  return ret_;
}
inline void CMsgLogout::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:msginfo.CMsgLogout.ret)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace msginfo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msginfo_2eproto__INCLUDED
